-- ============================================================
-- Metal Vault — User concert journal (manual log)
-- ============================================================
-- Adds two tables for the personal concert/show diary that the user
-- maintains in the "When's On → Concerts" tab. Up until this migration
-- the journal lived only in localStorage, so it never synced between
-- devices and was lost on browser data clears.
--
-- Built-in venue list (Madison Square Garden, Wacken, etc.) stays
-- hardcoded in app/concerts/ConcertsTab.js — only user-added venues
-- are persisted server-side. We therefore use TEXT for venue_id so the
-- column can hold either a built-in numeric id (stringified) or a
-- crypto.randomUUID() generated by the client when the user adds a
-- custom venue.
-- ============================================================

CREATE TABLE IF NOT EXISTS user_concerts (
  user_id     UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  client_id   TEXT NOT NULL,                                    -- crypto.randomUUID() from the client
  band        TEXT NOT NULL,
  venue_id    TEXT,                                             -- builtin int or user uuid, both as text
  year        TEXT,
  genre       TEXT DEFAULT 'Metal',
  rating      SMALLINT DEFAULT 0,
  price       TEXT DEFAULT '',
  note        TEXT DEFAULT '',
  created_at  TIMESTAMPTZ DEFAULT NOW(),
  updated_at  TIMESTAMPTZ DEFAULT NOW(),
  PRIMARY KEY (user_id, client_id)
);

CREATE TABLE IF NOT EXISTS user_venues (
  user_id     UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  client_id   TEXT NOT NULL,
  name        TEXT NOT NULL,
  city        TEXT DEFAULT '',
  cat         TEXT DEFAULT 'Other',
  created_at  TIMESTAMPTZ DEFAULT NOW(),
  PRIMARY KEY (user_id, client_id)
);

CREATE INDEX IF NOT EXISTS idx_user_concerts_user
  ON user_concerts(user_id, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_user_venues_user
  ON user_venues(user_id);

ALTER TABLE user_concerts ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_venues   ENABLE ROW LEVEL SECURITY;

-- Owner-only access, with WITH CHECK to also guard INSERT/UPDATE values
-- (matches the pattern in migration 021_rls_with_check.sql).
DROP POLICY IF EXISTS "Own concerts" ON user_concerts;
CREATE POLICY "Own concerts"
  ON user_concerts FOR ALL
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Own venues" ON user_venues;
CREATE POLICY "Own venues"
  ON user_venues FOR ALL
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- Auto-update timestamp on UPDATE
CREATE OR REPLACE FUNCTION user_concerts_touch_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS user_concerts_touch ON user_concerts;
CREATE TRIGGER user_concerts_touch
  BEFORE UPDATE ON user_concerts
  FOR EACH ROW EXECUTE FUNCTION user_concerts_touch_updated_at();
